// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD413w03WOQKlAG0xp_2k7_SpkwbRzHihU',
    appId: '1:757295359338:web:b97a02343474f344cd7113',
    messagingSenderId: '757295359338',
    projectId: 'fluttermac3pfinal',
    authDomain: 'fluttermac3pfinal.firebaseapp.com',
    storageBucket: 'fluttermac3pfinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMfv1PpxF0rNkF3-UxVaaPKry40iIY14',
    appId: '1:757295359338:android:0a7144ab79d7dce4cd7113',
    messagingSenderId: '757295359338',
    projectId: 'fluttermac3pfinal',
    storageBucket: 'fluttermac3pfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQwjmNfjZNtXSA-Rv2-DxGENtaL8lUZ8U',
    appId: '1:757295359338:ios:7fae4fe0b8df32eacd7113',
    messagingSenderId: '757295359338',
    projectId: 'fluttermac3pfinal',
    storageBucket: 'fluttermac3pfinal.appspot.com',
    iosBundleId: 'com.example.proyectoFinalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQwjmNfjZNtXSA-Rv2-DxGENtaL8lUZ8U',
    appId: '1:757295359338:ios:da3f44ec2e62a890cd7113',
    messagingSenderId: '757295359338',
    projectId: 'fluttermac3pfinal',
    storageBucket: 'fluttermac3pfinal.appspot.com',
    iosBundleId: 'com.example.proyectoFinalFlutter.RunnerTests',
  );
}
